wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 50
Loss fn:
  desc: null
  value: NCC, L2_norm
Optimizer:
  desc: null
  value: Adam
NCC Hyperparameters:
  desc: null
  value: 1
L2_norm Hyperparameters:
  desc: null
  value: 100
Batch Size:
  desc: null
  value: 5
NCC_Win_Size:
  desc: null
  value: 128
NCC denominator:
  desc: null
  value: 0.01
Epochs storage:
  desc: null
  value: /home-local/rudravg/Smoothness_100_epochs/
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715979211.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.12.1
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
